In [14]:
import pandas as pd
from datetime import datetime

In [15]:
daily=pd.read_csv('./KOSPI_1_years_daily_return_code.csv')

In [16]:
daily.set_index('Date', inplace=True)

In [17]:
daily

,000020,000040,000050,000070,000075,000080,000087,000100,000105,000120,...,452260,45226K,453340,456040,457190,460850,460860,462520,900140,950210
Date,,,,,,,,,,,,,,,,,,,,,
2022-09-06,0.105263,1.076923,1.612903,-0.298063,-0.335008,0.000000,0.000000,-0.712412,-0.179191,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.871795,0.925926
2022-09-07,-2.418507,-4.870624,0.000000,-1.943199,0.168067,-3.071672,-0.819672,-0.537675,0.000000,-2.575107,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.466115,-0.917431
2022-09-08,0.107759,-1.280000,-1.587302,2.743902,0.167785,-0.176056,-0.275482,0.180822,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.321543,1.851852
2022-09-13,3.444564,1.296596,2.419355,1.186944,-0.335008,3.350970,0.828729,0.898716,0.000000,2.643172,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.258547,5.000000
2022-09-14,-1.352758,-1.120000,-0.787402,-0.733138,-1.176471,-2.559727,-0.821918,-0.890711,-1.082746,-3.433476,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.189860,-3.030303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-28,0.417973,-0.792079,1.016949,0.285714,0.000000,-0.204186,-2.186879,-4.761905,-2.229299,2.922490,...,4.337723,0.555556,0.162734,0.982615,3.030303,5.277402,2.201258,22.473868,0.974659,0.630631
2023-08-29,0.104058,-0.399202,0.000000,0.997151,0.000000,0.306905,1.897019,0.972222,0.325733,-0.493827,...,0.148478,-0.331492,0.000000,-3.967066,-0.490196,11.311054,5.333333,-4.694168,-0.193050,1.432408
2023-08-30,4.054054,-1.402806,0.559284,-1.128350,0.000000,-0.866905,-0.066489,-0.137552,-0.487013,-1.488834,...,0.000000,1.108647,1.462226,-0.701481,29.802956,-2.424942,-1.655307,-2.686567,-0.193424,0.264784
2023-08-31,-0.199800,-1.016260,-1.112347,-0.427960,-0.386847,-0.154321,0.000000,0.275482,0.978793,-0.629723,...,-2.075612,-1.425439,0.720576,0.156986,6.641366,-3.550296,-1.782178,-5.981595,0.193798,1.496479
2023-09-01,-0.200200,2.258727,0.000000,-0.286533,0.970874,-0.412159,0.066534,-3.159341,-0.646204,4.309252,...,-0.151400,-0.333704,-0.874404,-1.410658,-12.099644,-3.312883,-1.512097,-3.099511,-1.353965,-2.948829

In [18]:
# 3일 연속 음봉 거르는 함수 만들기 / start_date 기준
def find_stocks_with_negative_returns(start_date,df='daily'): # df 디폴트를 daily로 설정
    negative_return_stocks = []
    
    # Calculate the index position of the start date
    start_date_index = df.index.get_loc(start_date)
    
    for column in df.columns:
        consecutive_negatives = 0
        for i in range(start_date_index, 0, -1):
            return_value = df[column].iloc[i]
            if return_value < 0:
                consecutive_negatives += 1
                if consecutive_negatives == 3:
                    negative_return_stocks.append(column)
                    break
            else:
                consecutive_negatives = 0
    
    return negative_return_stocks

In [ ]:
find_stocks_with_negative_returns()

In [19]:
def find_top_3_stocks_with_highest_mdd(start_date, df='daily'):
    # Find stocks with negative returns for three consecutive days leading up to the start_date
    negative_return_stocks = find_stocks_with_negative_returns(df, start_date)
    
    # Calculate MDD values for each selected stock from 3 days to 1 day before the start_date
    mdd_results = {}
    
    # Calculate the index position of the start date
    start_date_index = df.index.get_loc(start_date)
    
    for stock_code in negative_return_stocks:
        mdd_stock = []
        for i in range(start_date_index - 3, start_date_index):
            # Calculate MDD for the 3-day period
            three_day_returns = df.iloc[i:i+3][stock_code]
            mdd = (1 - three_day_returns / three_day_returns.max()).max()
            mdd_stock.append(mdd)
        mdd_results[stock_code] = mdd_stock
    
    # Rank stocks by MDD and select the top 3
    top_3_stocks = []
    
    for stock_code, mdd_values in mdd_results.items():
        if len(mdd_values) > 0:
            max_mdd = max(mdd_values)
            top_3_stocks.append((stock_code, max_mdd))
    
    top_3_stocks.sort(key=lambda x: x[1], reverse=True)
    top_3_stocks = top_3_stocks[:3]
    
    return top_3_stocks

In [35]:
find_top_3_stocks_with_highest_mdd(df=daily,start_date='20230901')

AttributeError: 'builtin_function_or_method' object has no attribute 'get_loc'

In [30]:
start_date = datetime(2023, 1, 2)
end_date = datetime(2023,9,1)
df=daily
average_returns = []

while start_date <= end_date:
    # Find the top 3 stocks with the highest MDD for the current start_date
    selected_top_3_stocks = find_top_3_stocks_with_highest_mdd(df, start_date.strftime('%Y-%m-%d'))
    
    # Calculate daily returns for the selected top 3 stocks on the current start_date
    daily_returns = calculate_daily_returns(df, start_date.strftime('%Y-%m-%d'), selected_top_3_stocks)
    
    # Calculate the average daily return and store it in a list
    average_return = daily_returns.mean()
    average_returns.append((start_date.strftime('%Y-%m-%d'), average_return))
    
    # Move to the next day
    # 거래일 기준이고 휴일이나 공휴일에는 자료가 없으니, 한칸이동했을때랑 하루더한거랑 같을 때만 실시
    if start_date.shift(-1)== start_date+timedelta(days=1):
        start_date += timedelta(days=1)
    elif start_date.shift(-1)== start_date+timedelta(days=2):
        start_date += timedelta(days=2)
    elif start_date.shift(-1)== start_date+timedelta(days=3):
        start_date += timedelta(days=3)
    elif start_date.shift(-1)== start_date+timedelta(days=4):
        start_date += timedelta(days=4)
    elif start_date.shift(-1)== start_date+timedelta(days=5):
        start_date += timedelta(days=5)
    elif start_date.shift(-1)== start_date+timedelta(days=6):
        start_date += timedelta(days=6)
    else :
        # Create a DataFrame for average returns
        average_df = pd.DataFrame(average_returns, columns=['Date', 'Average_Return'])
        average_df.set_index('Date', inplace=True)
        print("Average Daily Returns from 2023-01-01 to Today:")
        print(average_df)

AttributeError: 'builtin_function_or_method' object has no attribute 'get_loc'

In [31]:
r = daily.loc[impact] 
print(r)

NameError: name 'transactions' is not defined

In [20]:
def calculate_daily_returns(start_date, top_3_stocks,df='daily'):
    # Filter 'df' to include only the selected stocks and the 'start_date'
    selected_returns = df[top_3_stocks + [start_date]]
    
    # Calculate the daily returns for the selected stocks on the 'start_date'
    daily_returns = selected_returns.loc[start_date]
    
    return daily_returns

NameError: name 'df' is not defined